GET http://localhost:8080/api/todos/1

###

GET http://localhost:8080/api/todos

###

PUT http://localhost:8080/api/todos/2
Content-Type: application/json

{
  "id": 1,
  "task": "Buy milkfgdsfghdghdfg",
  "isCompleted": false,
  "deadline": "2020-09-11",
  "priority": "high"
}

###

DELETE http://localhost:8080/api/todos/1

###

POST http://localhost:8080/api/todos
Content-Type: application/json

{
"task": "Buy milk",
"deadline": "2020-09-11",
"priority": "high"
}

###
